// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PianificazioneTurni.Services.Pianificazione;

#nullable disable

namespace PianificazioneTurni.Migrations
{
    [DbContext(typeof(PianificazioneDbContext))]
    [Migration("20260207092021_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PianificazioneTurni.Services.Pianificazione.Assegnazione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DipendenteId")
                        .HasColumnType("int");

                    b.Property<int>("Fascia")
                        .HasColumnType("int");

                    b.Property<int>("NaveId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DipendenteId");

                    b.HasIndex("NaveId");

                    b.ToTable("Assegnazioni");
                });

            modelBuilder.Entity("PianificazioneTurni.Services.Pianificazione.Dipendente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Patente")
                        .HasColumnType("bit");

                    b.Property<string>("Ruolo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Scadenza")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Dipendenti");
                });

            modelBuilder.Entity("PianificazioneTurni.Services.Pianificazione.Nave", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataArrivo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataPartenza")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrarioArrivo")
                        .HasColumnType("int");

                    b.Property<int>("OrarioPartenza")
                        .HasColumnType("int");

                    b.Property<int?>("Pontile")
                        .HasColumnType("int");

                    b.Property<bool>("RichiedeAddettiSicurezza")
                        .HasColumnType("bit");

                    b.Property<bool>("RichiedeAddettiTerminal")
                        .HasColumnType("bit");

                    b.Property<bool>("RichiedeGruisti")
                        .HasColumnType("bit");

                    b.Property<bool>("RichiedeMulettisti")
                        .HasColumnType("bit");

                    b.Property<bool>("RichiedeOrmeggiatori")
                        .HasColumnType("bit");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Navi");
                });

            modelBuilder.Entity("PianificazioneTurni.Services.Pianificazione.Assegnazione", b =>
                {
                    b.HasOne("PianificazioneTurni.Services.Pianificazione.Dipendente", "Dipendente")
                        .WithMany("Assegnazioni")
                        .HasForeignKey("DipendenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PianificazioneTurni.Services.Pianificazione.Nave", "Nave")
                        .WithMany("Assegnazioni")
                        .HasForeignKey("NaveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dipendente");

                    b.Navigation("Nave");
                });

            modelBuilder.Entity("PianificazioneTurni.Services.Pianificazione.Dipendente", b =>
                {
                    b.Navigation("Assegnazioni");
                });

            modelBuilder.Entity("PianificazioneTurni.Services.Pianificazione.Nave", b =>
                {
                    b.Navigation("Assegnazioni");
                });
#pragma warning restore 612, 618
        }
    }
}
